### PR TITLE
Update Keyboard Shortcuts article to reflect Lessons shortcuts

### PR DESCRIPTION
**Pull request by edmilsonrobson**
I included the Lessons related shortcuts alongside the most recent changes we made to the Hotkeys pop-up (for Lessons).

### CODE REVIEW

**Comment by scottnicolson** [comment]
Should we not add more that just '`W` `A` `S` `D` Slide Navigation` ?  Could we can a context sentence otherwise this just repeats what is already available in the app.  Suggestion (note you can't use this image but I feel like having one would help):


Think of the wasd keys like the arrow keys but for your other hand.  `A` will move you left (aka previous slide) and `D` will move you right (aka forward one slide). For vocabulary lessons that have `Common Word Combinations / Patterns of Use ` the `W` key will move up through the different patterns of use, while `S` will move you down.

**Comment by edmilsonrobson** [comment]
> Should we not add more than just '`W` `A` `S` `D` Slide Navigation` ? Could we add a context sentence? Otherwise this just repeats what is already available in the app. Suggestion (note you can't use this image but I feel like having one would help):
> 
>  Think of the wasd keys like the arrow keys but for your other hand. `A` will move you left (aka previous slide) and `D` will move you right (aka forward one slide). For vocabulary lessons that have `Common Word Combinations / Patterns of Use ` the `W` key will move up through the different patterns of use, while `S` will move you down.

Interesting, I agree "Slide Navigation" might not give the full picture specially when you're not in the actual lessons page to try it out. I think your suggestion reads nicely, so I added it to the article. What do you think?

CleanShot 2022-10-13 at 15 06 40@2x

**Comment by edmilsonrobson** [comment]
Not sure if I have to tag the team manually, but @tofugu/wanikani-knowledgebase-editors - this is ready for review 😄

**Comment by JenKay** [comment]
Hey @edmilsonrobson , didn't even know there was a team called Knowledgebase editors, to be honest. Usually it's just @rachelcgrant and I updating the Guide so feel free to tag me directly next time, or ping me on Slack too and then assign it to me on the PR! If I'm away, then you can reach out to Rachel :)

I'll take a look and get back to you tomorrow.

**Comment by JenKay** [comment]
@edmilsonrobson Will there be a new screenshot at the bottom of the page? The current one just shows the old shortcuts. 
And I'm a bit confused between
W A S D Slide Navigation (see below)
← → Previous/Next Slide

Is there a difference between using ←  vs W or it's the same?

**Comment by edmilsonrobson** [comment]
> Hey @edmilsonrobson , didn't even know there was a team called Knowledgebase editors, to be honest. Usually it's just @rachelcgrant and I updating the Guide so feel free to tag me directly next time, or ping me on Slack too and then assign it to me on the PR! If I'm away, then you can reach out to Rachel :)
> 
> I'll take a look and get back to you tomorrow.

Ahh, got it! I followed this repository's [README](https://github.com/tofugu/wanikani-knowledge-guide), maybe we should update the knowledgebase editor teams to be you and Rachel only?



> @edmilsonrobson Will there be a new screenshot at the bottom of the page? The current one just shows the old shortcuts. And I'm a bit confused between W A S D Slide Navigation (see below) ← → Previous/Next Slide
> 
> Is there a difference between using ← vs W or it's the same?

Regarding the screenshot, the shortcuts displayed there are for Reviews, which were not changed. We could have another screenshot showing the Lessons shortcuts, but since the gif is there mainly to give the users direction on where to find the shortcut list (at the bottom-right of the screen), having another gif displaying the same thing for Lessons felt a bit redundant to me. Or do you think there's value in having another gif showcasing both the Lessons and the Reviews shortcut list button?

Regarding arrow keys vs WASD, using the left/right arrows is equivalent to using the `A` and `D` keys. `W` and `S` are for vertical selections, which currently only happens for vocabularies with Patterns of Use. Scott suggested the text below the Lessons shortcut list to better communicate what `WASD` really does. Do you have any suggestions on how to bring more clarity to the article?

Thanks :)

**Comment by JenKay** [comment]
> Regarding arrow keys vs WASD, using the left/right arrows is equivalent to using the `A` and `D` keys. `W` and `S` are for vertical selections, which currently only happens for vocabularies with Patterns of Use. S

Ah yes, that's what I meant, hah, A for the left arrow. That's why I was confused at first since these two kinda do the same thing, other than adding the new vertical options: 
C69C78D0-812C-4541-B626-8B60F4654FD3

I think Scott's text is fine!

To be honest, I've never read that README because this repo's been around for a while before I joined and the only people really working on the Knowledge Guide is just Support anyway (Javi also used to sometimes update). I don't think I can edit that editors team group anyway so feel free to just tag me if you have any future KG-related questions or PRs. I list my vacation on the company calendar though so you might want to check that before tagging if you need a quick response!  You can tag Rachel if I'm away.

**Review by JenKay — APPROVED** [review]

**Pull request merged**
